import * as XLSX from 'xlsx';
import { MappedFact, SagExportOptions } from '../types';

// 1. Generate SAG Gen XBRL native XAG / XML import document
export function generateSagXagContent(facts: MappedFact[], options: SagExportOptions): string {
  const isIndAs = options.taxonomy === 'IND_AS';
  const taxonomyNs = isIndAs 
    ? 'http://www.mca.gov.in/XBRL/2016/IndAS' 
    : 'http://www.mca.gov.in/XBRL/2015/NonIndAS';
  
  const now = new Date().toISOString();

  let xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by XBRL AI Agent for SAG Gen XBRL -->
<!-- Compatible with SAG Gen XBRL 2023/2024/2025 Release -->
<SAGGenXBRLExport version="2024.2" generator="XBRL_AI_Agent" exportedAt="${now}">
  <FilingMetadata>
    <TaxonomyStandard>${options.taxonomy}</TaxonomyStandard>
    <TaxonomyNamespace>${taxonomyNs}</TaxonomyNamespace>
    <FilingType>${options.natureOfReport}</FilingType>
    <UnitScale>${options.unitScale}</UnitScale>
  </FilingMetadata>
  <CompanyProfile>
    <CIN>${escapeXml(options.companyCin)}</CIN>
    <CompanyName>${escapeXml(options.companyName)}</CompanyName>
    <FinancialYearStartDate>${options.yearStartDate}</FinancialYearStartDate>
    <FinancialYearEndDate>${options.yearEndDate}</FinancialYearEndDate>
    <Currency>INR</Currency>
  </CompanyProfile>
  <Taggings count="${facts.length}">
`;

  facts.forEach(fact => {
    const cyVal = fact.currentValue !== null && fact.currentValue !== undefined ? fact.currentValue : '';
    const pyVal = fact.previousValue !== null && fact.previousValue !== undefined ? fact.previousValue : '';
    const fieldId = fact.sagFieldId || '';
    const screenRef = fact.sagScreenRef || '';
    
    xml += `    <Fact sagFieldId="${escapeXml(fieldId)}" sagScreenRef="${escapeXml(screenRef)}" concept="${escapeXml(fact.conceptName)}" schedule="${escapeXml(fact.schedule)}" period="${escapeXml(fact.period)}" unit="${escapeXml(fact.unit)}" status="${fact.status}" confidence="${fact.confidence}">
      <Label>${escapeXml(fact.label)}</Label>
      <CurrentYearValue>${escapeXml(String(cyVal))}</CurrentYearValue>
      <PreviousYearValue>${escapeXml(String(pyVal))}</PreviousYearValue>
      <SourceDocument>${escapeXml(fact.sourceDoc || '')}</SourceDocument>
      <SourcePageOrSheet>${escapeXml(fact.sourcePageOrSheet || '')}</SourcePageOrSheet>
    </Fact>\n`;
  });

  xml += `  </Taggings>
  <AutomationBridge>
    <SagAutoFillEnabled>true</SagAutoFillEnabled>
    <PreservePriorYearDimensions>true</PreservePriorYearDimensions>
    <DirectDatabaseWriteSupported>false</DirectDatabaseWriteSupported>
    <DirectLocalWindowsAgentRequired>true</DirectLocalWindowsAgentRequired>
  </AutomationBridge>
</SAGGenXBRLExport>`;

  return xml;
}

// 2. Generate SAG Gen XBRL Multi-Sheet Excel Import Template (.xlsx)
export function generateSagExcelWorkbook(facts: MappedFact[], options: SagExportOptions): Uint8Array {
  const wb = XLSX.utils.book_new();

  // Sheet 1: General Info
  const genInfoData = [
    ['SAG Gen XBRL - General Information Sheet', ''],
    ['CIN', options.companyCin],
    ['Company Name', options.companyName],
    ['Financial Year Start', options.yearStartDate],
    ['Financial Year End', options.yearEndDate],
    ['Taxonomy Mode', options.taxonomy],
    ['Nature of Financial Statements', options.natureOfReport],
    ['Unit Scale for Currency', options.unitScale],
    ['Generated by', 'XBRL AI Agent Autonomous Engine']
  ];
  const wsGenInfo = XLSX.utils.aoa_to_sheet(genInfoData);
  XLSX.utils.book_append_sheet(wb, wsGenInfo, 'General_Info');

  // Sheet 2: Balance Sheet
  const bsFacts = facts.filter(f => f.schedule === 'BALANCE_SHEET');
  const bsData = [
    ['Concept Tag', 'Line Item Description', 'Current Year (CY)', 'Previous Year (PY)', 'Unit', 'Mapping Status', 'Confidence %'],
    ...bsFacts.map(f => [
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status,
      `${f.confidence}%`
    ])
  ];
  const wsBs = XLSX.utils.aoa_to_sheet(bsData);
  XLSX.utils.book_append_sheet(wb, wsBs, 'Balance_Sheet');

  // Sheet 3: Profit and Loss
  const plFacts = facts.filter(f => f.schedule === 'PROFIT_LOSS');
  const plData = [
    ['Concept Tag', 'Line Item Description', 'Current Year (CY)', 'Previous Year (PY)', 'Unit', 'Mapping Status', 'Confidence %'],
    ...plFacts.map(f => [
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status,
      `${f.confidence}%`
    ])
  ];
  const wsPl = XLSX.utils.aoa_to_sheet(plData);
  XLSX.utils.book_append_sheet(wb, wsPl, 'Profit_and_Loss');

  // Sheet 4: CARO & Notes
  const otherFacts = facts.filter(f => f.schedule === 'CARO' || f.schedule === 'GENERAL' || f.schedule === 'NOTES');
  const otherData = [
    ['Schedule', 'Concept Tag', 'Description', 'Current Value', 'Previous Value', 'Unit', 'Status'],
    ...otherFacts.map(f => [
      f.schedule,
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status
    ])
  ];
  const wsOther = XLSX.utils.aoa_to_sheet(otherData);
  XLSX.utils.book_append_sheet(wb, wsOther, 'Notes_and_CARO');

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Uint8Array(out);
}

// 3. Generate Official MCA XBRL Instance Document (.xml)
export function generateMcaXbrlInstance(facts: MappedFact[], options: SagExportOptions): string {
  const isIndAs = options.taxonomy === 'IND_AS';
  const prefix = isIndAs ? 'ind-as' : 'in-ca';
  const schemaRef = isIndAs
    ? 'http://www.mca.gov.in/XBRL/2016/IndAS/mca-ind-as-2016-10-31.xsd'
    : 'http://www.mca.gov.in/XBRL/2015/NonIndAS/mca-non-ind-as-2015-03-31.xsd';

  const cyInstant = `CY_Instant_${options.yearEndDate.replace(/-/g, '')}`;
  const cyDuration = `CY_Duration_${options.yearStartDate.replace(/-/g, '')}_${options.yearEndDate.replace(/-/g, '')}`;
  const pyInstant = `PY_Instant_${parseInt(options.yearEndDate.slice(0, 4)) - 1}0331`;

  let xml = `<?xml version="1.0" encoding="utf-8"?>
<xbrli:xbrl
  xmlns:${prefix}="${isIndAs ? 'http://www.mca.gov.in/XBRL/2016/IndAS' : 'http://www.mca.gov.in/XBRL/2015/NonIndAS'}"
  xmlns:xbrli="http://www.xbrl.org/2003/instance"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:link="http://www.xbrl.org/2003/linkbase"
  xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <link:schemaRef xlink:type="simple" xlink:href="${schemaRef}" />

  <!-- Context: Current Year Instant -->
  <xbrli:context id="${cyInstant}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in/cin">${options.companyCin}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:instant>${options.yearEndDate}</xbrli:instant>
    </xbrli:period>
  </xbrli:context>

  <!-- Context: Current Year Duration -->
  <xbrli:context id="${cyDuration}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in/cin">${options.companyCin}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>${options.yearStartDate}</xbrli:startDate>
      <xbrli:endDate>${options.yearEndDate}</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>

  <!-- Units -->
  <xbrli:unit id="INR">
    <xbrli:measure>iso4217:INR</xbrli:measure>
  </xbrli:unit>
  <xbrli:unit id="Pure">
    <xbrli:measure>xbrli:pure</xbrli:measure>
  </xbrli:unit>
  <xbrli:unit id="Shares">
    <xbrli:measure>xbrli:shares</xbrli:measure>
  </xbrli:unit>

  <!-- Facts Data Generated Automatically -->
`;

  facts.forEach(fact => {
    if (fact.currentValue === null || fact.currentValue === undefined || fact.currentValue === '') return;

    const isDuration = fact.period.toLowerCase().includes('duration') || fact.schedule === 'PROFIT_LOSS' || fact.schedule === 'CARO';
    const contextRef = isDuration ? cyDuration : cyInstant;
    const isMonetary = fact.unit === 'INR';
    const unitAttr = isMonetary ? ' unitRef="INR" decimals="-5"' : fact.unit === 'pure' ? ' unitRef="Pure" decimals="2"' : '';

    xml += `  <${fact.conceptName} contextRef="${contextRef}"${unitAttr}>${escapeXml(String(fact.currentValue))}</${fact.conceptName}>\n`;
  });

  xml += `</xbrli:xbrl>`;
  return xml;
}

// 4. Generate Windows Automated SAG Gen XBRL Script (.vbs)
export function generateSagWindowsScript(options: SagExportOptions): string {
  return `' =========================================================================
' SAG Gen XBRL Autonomous Auto-Write & Direct Import Script
' Generated by XBRL AI Agent for SAG Infotech Gen XBRL
' Company CIN: ${options.companyCin}
' Company Name: ${options.companyName}
' Taxonomy: ${options.taxonomy}
' =========================================================================

Option Explicit
Dim fso, shell, sagPath, candidatePaths, p, installFound
Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

candidatePaths = Array( _
  "C:\\Program Files\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "C:\\Program Files (x86)\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "M:\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "D:\\SAG Infotech\\GenXBRL\\GenXBRL.exe" _
)

installFound = ""
For Each p In candidatePaths
  If fso.FileExists(p) Then
    installFound = p
    Exit For
  End If
Next

If installFound = "" Then
  WScript.Echo "SAG Gen XBRL executable was not found in standard installation paths." & vbCrLf & _
               "Please ensure SAG Gen XBRL is installed, or launch Gen XBRL manually and import the generated SAG_Import.xlsx or SAG_Import.xag."
  WScript.Quit 1
End If

WScript.Echo "Found SAG Gen XBRL: " & installFound & vbCrLf & _
             "Writing company data for ${options.companyCin}..."

' Copy pre-generated SAG XAG payload into SAG Import queue
Dim appDataSag, scriptDir
scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
appDataSag = shell.ExpandEnvironmentStrings("%APPDATA%") & "\\SAG Infotech\\GenXBRL\\ImportQueue\\"

If Not fso.FolderExists(appDataSag) Then
  On Error Resume Next
  fso.CreateFolder(appDataSag)
  On Error GoTo 0
End If

If fso.FileExists(scriptDir & "\\SAG_GenXBRL_Import.xag") Then
  fso.CopyFile scriptDir & "\\SAG_GenXBRL_Import.xag", appDataSag & "${options.companyCin}_import.xag", True
  WScript.Echo "Data successfully staged into SAG Gen XBRL Import queue!"
End If

' Launch SAG Gen XBRL with Company CIN argument
shell.Run Chr(34) & installFound & Chr(34) & " /CIN=${options.companyCin} /IMPORT=" & Chr(34) & scriptDir & "\\SAG_GenXBRL_Import.xag" & Chr(34), 1, False

WScript.Echo "SAG Gen XBRL launched. Data auto-fill sequence initiated."
`;
}

// 5. Generate Windows PowerShell Autonomous Script (.ps1)
export function generatePowerShellScript(options: SagExportOptions): string {
  return `# =========================================================================
# SAG Gen XBRL Autonomous Auto-Write & Direct Import PowerShell Script
# Company CIN: ${options.companyCin} (${options.companyName})
# =========================================================================

Write-Host "=================================================" -ForegroundColor Cyan
Write-Host " XBRL AI AGENT -> SAG GEN XBRL AUTO-WRITER " -ForegroundColor Yellow
Write-Host "=================================================" -ForegroundColor Cyan

$candidatePaths = @(
  "C:\\Program Files\\SAG Infotech\\GenXBRL\\GenXBRL.exe",
  "C:\\Program Files (x86)\\SAG Infotech\\GenXBRL\\GenXBRL.exe",
  "M:\\SAG Infotech\\GenXBRL\\GenXBRL.exe",
  "D:\\SAG Infotech\\GenXBRL\\GenXBRL.exe"
)

$sagExe = $null
foreach ($path in $candidatePaths) {
  if (Test-Path $path) {
    $sagExe = $path
    break
  }
}

if (-not $sagExe) {
  Write-Warning "Could not detect default GenXBRL.exe installation."
  Write-Host "You can manually import the generated SAG_Import.xlsx or SAG_Import.xag into SAG Gen XBRL."
  exit 1
}

Write-Host "[+] Found SAG Gen XBRL at: $sagExe" -ForegroundColor Green
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$xagFile = Join-Path $scriptDir "SAG_GenXBRL_${options.companyCin}.xag"
$excelFile = Join-Path $scriptDir "SAG_GenXBRL_Import_${options.companyCin}.xlsx"

# Stage in AppData import queue
$appDataQueue = "$env:APPDATA\\SAG Infotech\\GenXBRL\\ImportQueue"
if (-not (Test-Path $appDataQueue)) {
  New-Item -ItemType Directory -Path $appDataQueue -Force | Out-Null
}

if (Test-Path $xagFile) {
  Copy-Item -Path $xagFile -Destination (Join-Path $appDataQueue "${options.companyCin}.xag") -Force
  Write-Host "[+] Staged .xag data into SAG import queue." -ForegroundColor Green
}

Write-Host "[*] Launching SAG Gen XBRL in auto-fill mode..." -ForegroundColor Cyan
Start-Process -FilePath $sagExe -ArgumentList ('/CIN=' + '${options.companyCin}' + ' /IMPORT=' + '\"' + $xagFile + '\"')

Write-Host "[+] Auto-fill executed successfully! Please review the auto-populated figures in SAG Gen XBRL." -ForegroundColor Green
`;
}

// 6. Generate Robotic GUI AutoHotkey Script (.ahk)
export function generateAutoHotkeyScript(options: SagExportOptions): string {
  return `; =========================================================================
; AutoHotkey Script: Autonomous GUI Auto-Fill for SAG Gen XBRL
; Automatically focuses Gen XBRL window and navigates/pastes financial facts
; =========================================================================
#NoEnv
SetWorkingDir %A_ScriptDir%
CoordMode, Mouse, Window
SetTitleMatchMode, 2

MsgBox, 64, XBRL AI Agent, Preparing to auto-fill SAG Gen XBRL for ${options.companyCin}. Please ensure SAG Gen XBRL is open with your client selected. Click OK to start., 5

IfWinExist, Gen XBRL
{
    WinActivate, Gen XBRL
    WinWaitActive, Gen XBRL, , 3
    Sleep, 500
    
    ; Trigger Import Menu
    Send, !t ; Alt+T (Tools menu)
    Sleep, 300
    Send, i ; Import submenu
    Sleep, 300
    Send, {Enter}
    Sleep, 800
    
    ; Send Path to generated Excel or XAG file
    SendInput, %A_ScriptDir%\\SAG_GenXBRL_Import_${options.companyCin}.xlsx
    Sleep, 500
    Send, {Enter}
    
    TrayTip, XBRL AI Agent, SAG Gen XBRL auto-fill sequence completed successfully!, 5
}
Else
{
    MsgBox, 48, SAG Gen XBRL Not Running, Please open SAG Gen XBRL first, then re-run this script to auto-fill.
}
Return
`;
}

// 7. Generate SAG Gen XBRL Structured CSV Import File (.csv)
export function generateSagCsvContent(facts: MappedFact[], options: SagExportOptions): string {
  const headers = [
    'SAG_Field_ID',
    'SAG_Screen_Reference',
    'Concept_Code',
    'Concept_Description',
    'Schedule_Name',
    'Period_Context',
    'Current_Year_Value',
    'Previous_Year_Value',
    'Monetary_Unit',
    'Decimals',
    'Mapping_Status',
    'Confidence_Score',
    'Source_Document',
    'Source_Page_Or_Sheet',
    'Company_CIN',
    'Taxonomy_Standard'
  ];

  const rows = facts.map(fact => {
    const isDuration = fact.period.toLowerCase().includes('duration') || fact.schedule === 'PROFIT_LOSS' || fact.schedule === 'CARO';
    const decimals = fact.unit === 'INR' ? (options.unitScale === 'LAKHS' ? '-5' : options.unitScale === 'CRORES' ? '-7' : '0') : fact.unit === 'pure' ? '2' : '0';
    const cy = fact.currentValue !== null && fact.currentValue !== undefined ? String(fact.currentValue) : '';
    const py = fact.previousValue !== null && fact.previousValue !== undefined ? String(fact.previousValue) : '';
    const fieldId = fact.sagFieldId || '';
    const screenRef = fact.sagScreenRef || '';

    return [
      escapeCsv(fieldId),
      escapeCsv(screenRef),
      escapeCsv(fact.conceptName),
      escapeCsv(fact.label),
      escapeCsv(fact.schedule),
      escapeCsv(isDuration ? 'Duration' : 'Instant'),
      escapeCsv(cy),
      escapeCsv(py),
      escapeCsv(fact.unit),
      decimals,
      escapeCsv(fact.status),
      `${fact.confidence}%`,
      escapeCsv(fact.sourceDoc || ''),
      escapeCsv(fact.sourcePageOrSheet || ''),
      escapeCsv(options.companyCin),
      escapeCsv(options.taxonomy)
    ].join(',');
  });

  return [headers.join(','), ...rows].join('\r\n');
}

// 8. Generate SAG Gen XBRL Structured Interchange JSON (.json)
export function generateSagJsonContent(facts: MappedFact[], options: SagExportOptions): string {
  const decimals = options.unitScale === 'LAKHS' ? -5 : options.unitScale === 'CRORES' ? -7 : 0;

  const payload = {
    schemaVersion: "SAG_GENXBRL_2024.2",
    format: "SAG_XBRL_DATA_BRIDGE_JSON",
    generator: "XBRL_AI_Agent",
    exportedAt: new Date().toISOString(),
    companyProfile: {
      cin: options.companyCin,
      companyName: options.companyName,
      financialYearStart: options.yearStartDate,
      financialYearEnd: options.yearEndDate,
      taxonomyStandard: options.taxonomy,
      natureOfReport: options.natureOfReport,
      unitScale: options.unitScale,
      currency: "INR",
      defaultDecimals: decimals
    },
    statistics: {
      totalFacts: facts.length,
      confirmedFacts: facts.filter(f => f.status === 'CONFIRMED').length,
      changedFacts: facts.filter(f => f.status === 'CHANGED').length,
      reviewRequiredFacts: facts.filter(f => f.status === 'REVIEW_REQUIRED').length
    },
    taggings: facts.map(fact => {
      const isDuration = fact.period.toLowerCase().includes('duration') || fact.schedule === 'PROFIT_LOSS' || fact.schedule === 'CARO';
      const variance = (typeof fact.currentValue === 'number' && typeof fact.previousValue === 'number' && fact.previousValue !== 0)
        ? {
            amount: fact.currentValue - fact.previousValue,
            percentage: Number((((fact.currentValue - fact.previousValue) / Math.abs(fact.previousValue)) * 100).toFixed(2))
          }
        : null;

      return {
        sagFieldId: fact.sagFieldId || null,
        sagScreenRef: fact.sagScreenRef || null,
        conceptCode: fact.conceptName,
        label: fact.label,
        schedule: fact.schedule,
        periodType: isDuration ? 'duration' : 'instant',
        periodContext: fact.period,
        unit: fact.unit,
        decimals: fact.unit === 'INR' ? decimals : fact.unit === 'pure' ? 2 : 0,
        currentYearValue: fact.currentValue,
        previousYearValue: fact.previousValue,
        variance,
        status: fact.status,
        confidence: fact.confidence,
        sourceDocument: fact.sourceDoc || null,
        sourcePageOrSheet: fact.sourcePageOrSheet || null,
        reviewNotes: fact.reviewNotes || null
      };
    })
  };

  return JSON.stringify(payload, null, 2);
}

function escapeCsv(field: string): string {
  if (field.includes(',') || field.includes('"') || field.includes('\n') || field.includes('\r')) {
    return `"${field.replace(/"/g, '""')}"`;
  }
  return field;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
