import * as XLSX from 'xlsx';
import { MappedFact, SagExportOptions } from '../types';

// 1. Generate SAG Gen XBRL native XAG / XML import document
export function generateSagXagContent(facts: MappedFact[], options: SagExportOptions): string {
  const isIndAs = options.taxonomy === 'IND_AS';
  const taxonomyNs = isIndAs 
    ? 'http://www.mca.gov.in/XBRL/2016/IndAS' 
    : 'http://www.mca.gov.in/XBRL/2015/NonIndAS';
  
  const now = new Date().toISOString();

  let xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by XBRL AI Agent for SAG Gen XBRL -->
<!-- Compatible with SAG Gen XBRL 2023/2024/2025 Release -->
<SAGGenXBRLExport version="2024.2" generator="XBRL_AI_Agent" exportedAt="${now}">
  <FilingMetadata>
    <TaxonomyStandard>${options.taxonomy}</TaxonomyStandard>
    <TaxonomyNamespace>${taxonomyNs}</TaxonomyNamespace>
    <FilingType>${options.natureOfReport}</FilingType>
    <UnitScale>${options.unitScale}</UnitScale>
  </FilingMetadata>
  <CompanyProfile>
    <CIN>${escapeXml(options.companyCin)}</CIN>
    <CompanyName>${escapeXml(options.companyName)}</CompanyName>
    <FinancialYearStartDate>${options.yearStartDate}</FinancialYearStartDate>
    <FinancialYearEndDate>${options.yearEndDate}</FinancialYearEndDate>
    <Currency>INR</Currency>
  </CompanyProfile>
  <Taggings count="${facts.length}">
`;

  facts.forEach(fact => {
    const cyVal = fact.currentValue !== null && fact.currentValue !== undefined ? fact.currentValue : '';
    const pyVal = fact.previousValue !== null && fact.previousValue !== undefined ? fact.previousValue : '';
    
    xml += `    <Fact concept="${escapeXml(fact.conceptName)}" schedule="${escapeXml(fact.schedule)}" period="${escapeXml(fact.period)}" unit="${escapeXml(fact.unit)}" status="${fact.status}" confidence="${fact.confidence}">
      <Label>${escapeXml(fact.label)}</Label>
      <CurrentYearValue>${escapeXml(String(cyVal))}</CurrentYearValue>
      <PreviousYearValue>${escapeXml(String(pyVal))}</PreviousYearValue>
      <SourceDocument>${escapeXml(fact.sourceDoc || '')}</SourceDocument>
      <SourcePageOrSheet>${escapeXml(fact.sourcePageOrSheet || '')}</SourcePageOrSheet>
    </Fact>\n`;
  });

  xml += `  </Taggings>
  <AutomationBridge>
    <SagAutoFillEnabled>true</SagAutoFillEnabled>
    <PreservePriorYearDimensions>true</PreservePriorYearDimensions>
    <DirectDatabaseWriteSupported>true</DirectDatabaseWriteSupported>
  </AutomationBridge>
</SAGGenXBRLExport>`;

  return xml;
}

// 2. Generate SAG Gen XBRL Multi-Sheet Excel Import Template (.xlsx)
export function generateSagExcelWorkbook(facts: MappedFact[], options: SagExportOptions): Uint8Array {
  const wb = XLSX.utils.book_new();

  // Sheet 1: General Info
  const genInfoData = [
    ['SAG Gen XBRL - General Information Sheet', ''],
    ['CIN', options.companyCin],
    ['Company Name', options.companyName],
    ['Financial Year Start', options.yearStartDate],
    ['Financial Year End', options.yearEndDate],
    ['Taxonomy Mode', options.taxonomy],
    ['Nature of Financial Statements', options.natureOfReport],
    ['Unit Scale for Currency', options.unitScale],
    ['Generated by', 'XBRL AI Agent Autonomous Engine']
  ];
  const wsGenInfo = XLSX.utils.aoa_to_sheet(genInfoData);
  XLSX.utils.book_append_sheet(wb, wsGenInfo, 'General_Info');

  // Sheet 2: Balance Sheet
  const bsFacts = facts.filter(f => f.schedule === 'BALANCE_SHEET');
  const bsData = [
    ['Concept Tag', 'Line Item Description', 'Current Year (CY)', 'Previous Year (PY)', 'Unit', 'Mapping Status', 'Confidence %'],
    ...bsFacts.map(f => [
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status,
      `${f.confidence}%`
    ])
  ];
  const wsBs = XLSX.utils.aoa_to_sheet(bsData);
  XLSX.utils.book_append_sheet(wb, wsBs, 'Balance_Sheet');

  // Sheet 3: Profit and Loss
  const plFacts = facts.filter(f => f.schedule === 'PROFIT_LOSS');
  const plData = [
    ['Concept Tag', 'Line Item Description', 'Current Year (CY)', 'Previous Year (PY)', 'Unit', 'Mapping Status', 'Confidence %'],
    ...plFacts.map(f => [
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status,
      `${f.confidence}%`
    ])
  ];
  const wsPl = XLSX.utils.aoa_to_sheet(plData);
  XLSX.utils.book_append_sheet(wb, wsPl, 'Profit_and_Loss');

  // Sheet 4: CARO & Notes
  const otherFacts = facts.filter(f => f.schedule === 'CARO' || f.schedule === 'GENERAL' || f.schedule === 'NOTES');
  const otherData = [
    ['Schedule', 'Concept Tag', 'Description', 'Current Value', 'Previous Value', 'Unit', 'Status'],
    ...otherFacts.map(f => [
      f.schedule,
      f.conceptName,
      f.label,
      f.currentValue,
      f.previousValue,
      f.unit,
      f.status
    ])
  ];
  const wsOther = XLSX.utils.aoa_to_sheet(otherData);
  XLSX.utils.book_append_sheet(wb, wsOther, 'Notes_and_CARO');

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Uint8Array(out);
}

// 3. Generate Official MCA XBRL Instance Document (.xml)
export function generateMcaXbrlInstance(facts: MappedFact[], options: SagExportOptions): string {
  const isIndAs = options.taxonomy === 'IND_AS';
  const prefix = isIndAs ? 'ind-as' : 'in-ca';
  const schemaRef = isIndAs
    ? 'http://www.mca.gov.in/XBRL/2016/IndAS/mca-ind-as-2016-10-31.xsd'
    : 'http://www.mca.gov.in/XBRL/2015/NonIndAS/mca-non-ind-as-2015-03-31.xsd';

  const cyInstant = `CY_Instant_${options.yearEndDate.replace(/-/g, '')}`;
  const cyDuration = `CY_Duration_${options.yearStartDate.replace(/-/g, '')}_${options.yearEndDate.replace(/-/g, '')}`;
  const pyInstant = `PY_Instant_${parseInt(options.yearEndDate.slice(0, 4)) - 1}0331`;

  let xml = `<?xml version="1.0" encoding="utf-8"?>
<xbrli:xbrl
  xmlns:${prefix}="${isIndAs ? 'http://www.mca.gov.in/XBRL/2016/IndAS' : 'http://www.mca.gov.in/XBRL/2015/NonIndAS'}"
  xmlns:xbrli="http://www.xbrl.org/2003/instance"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:link="http://www.xbrl.org/2003/linkbase"
  xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <link:schemaRef xlink:type="simple" xlink:href="${schemaRef}" />

  <!-- Context: Current Year Instant -->
  <xbrli:context id="${cyInstant}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in/cin">${options.companyCin}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:instant>${options.yearEndDate}</xbrli:instant>
    </xbrli:period>
  </xbrli:context>

  <!-- Context: Current Year Duration -->
  <xbrli:context id="${cyDuration}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in/cin">${options.companyCin}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>${options.yearStartDate}</xbrli:startDate>
      <xbrli:endDate>${options.yearEndDate}</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>

  <!-- Units -->
  <xbrli:unit id="INR">
    <xbrli:measure>iso4217:INR</xbrli:measure>
  </xbrli:unit>
  <xbrli:unit id="Pure">
    <xbrli:measure>xbrli:pure</xbrli:measure>
  </xbrli:unit>
  <xbrli:unit id="Shares">
    <xbrli:measure>xbrli:shares</xbrli:measure>
  </xbrli:unit>

  <!-- Facts Data Generated Automatically -->
`;

  facts.forEach(fact => {
    if (fact.currentValue === null || fact.currentValue === undefined || fact.currentValue === '') return;

    const isDuration = fact.period.toLowerCase().includes('duration') || fact.schedule === 'PROFIT_LOSS' || fact.schedule === 'CARO';
    const contextRef = isDuration ? cyDuration : cyInstant;
    const isMonetary = fact.unit === 'INR';
    const unitAttr = isMonetary ? ' unitRef="INR" decimals="-5"' : fact.unit === 'pure' ? ' unitRef="Pure" decimals="2"' : '';

    xml += `  <${fact.conceptName} contextRef="${contextRef}"${unitAttr}>${escapeXml(String(fact.currentValue))}</${fact.conceptName}>\n`;
  });

  xml += `</xbrli:xbrl>`;
  return xml;
}

// 4. Generate Windows Automated SAG Gen XBRL Script (.vbs / .ps1)
export function generateSagWindowsScript(options: SagExportOptions): string {
  return `' =========================================================================
' SAG Gen XBRL Autonomous Auto-Write & Direct Import Script
' Generated by XBRL AI Agent for SAG Infotech Gen XBRL
' Company CIN: ${options.companyCin}
' Company Name: ${options.companyName}
' Taxonomy: ${options.taxonomy}
' =========================================================================

Option Explicit
Dim fso, shell, sagPath, candidatePaths, p, installFound
Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

candidatePaths = Array( _
  "C:\\Program Files\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "C:\\Program Files (x86)\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "M:\\SAG Infotech\\GenXBRL\\GenXBRL.exe", _
  "D:\\SAG Infotech\\GenXBRL\\GenXBRL.exe" _
)

installFound = ""
For Each p In candidatePaths
  If fso.FileExists(p) Then
    installFound = p
    Exit For
  End If
Next

If installFound = "" Then
  WScript.Echo "SAG Gen XBRL executable was not found in standard installation paths." & vbCrLf & _
               "Please ensure SAG Gen XBRL is installed, or launch Gen XBRL manually and import the generated SAG_Import.xlsx or SAG_Import.xag."
  WScript.Quit 1
End If

WScript.Echo "Found SAG Gen XBRL: " & installFound & vbCrLf & _
             "Writing company data for ${options.companyCin}..."

' Copy pre-generated SAG XAG payload into SAG Import queue
Dim appDataSag, scriptDir
scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
appDataSag = shell.ExpandEnvironmentStrings("%APPDATA%") & "\\SAG Infotech\\GenXBRL\\ImportQueue\\"

If Not fso.FolderExists(appDataSag) Then
  On Error Resume Next
  fso.CreateFolder(appDataSag)
  On Error GoTo 0
End If

If fso.FileExists(scriptDir & "\\SAG_GenXBRL_Import.xag") Then
  fso.CopyFile scriptDir & "\\SAG_GenXBRL_Import.xag", appDataSag & "${options.companyCin}_import.xag", True
  WScript.Echo "Data successfully staged into SAG Gen XBRL Import queue!"
End If

' Launch SAG Gen XBRL with Company CIN argument
shell.Run Chr(34) & installFound & Chr(34) & " /CIN=${options.companyCin} /IMPORT=" & Chr(34) & scriptDir & "\\SAG_GenXBRL_Import.xag" & Chr(34), 1, False

WScript.Echo "SAG Gen XBRL launched. Data auto-fill sequence initiated."
`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
