using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace XBRLAIAgent;

public static class SagGenXbrlExporter
{
    public static string GenerateXag(IReadOnlyList<MappedFact> facts, SagExportOptions options)
    {
        var sb = new StringBuilder();
        var ns = options.Taxonomy == TaxonomyStandard.IndAS
            ? "http://www.mca.gov.in/XBRL/2016/IndAS"
            : "http://www.mca.gov.in/XBRL/2015/NonIndAS";

        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine("<!-- Generated by XBRL AI Agent for SAG Gen XBRL -->");
        sb.AppendLine($"<SAGGenXBRLExport version=\"2024.2\" generator=\"XBRL_AI_Agent\" exportedAt=\"{DateTime.UtcNow:O}\">");
        sb.AppendLine("  <FilingMetadata>");
        sb.AppendLine($"    <TaxonomyStandard>{options.Taxonomy}</TaxonomyStandard>");
        sb.AppendLine($"    <TaxonomyNamespace>{ns}</TaxonomyNamespace>");
        sb.AppendLine($"    <FilingType>{options.NatureOfReport}</FilingType>");
        sb.AppendLine($"    <UnitScale>{options.UnitScale}</UnitScale>");
        sb.AppendLine("  </FilingMetadata>");
        sb.AppendLine("  <CompanyProfile>");
        sb.AppendLine($"    <CIN>{EscapeXml(options.CompanyCin)}</CIN>");
        sb.AppendLine($"    <CompanyName>{EscapeXml(options.CompanyName)}</CompanyName>");
        sb.AppendLine($"    <FinancialYearStartDate>{options.YearStartDate}</FinancialYearStartDate>");
        sb.AppendLine($"    <FinancialYearEndDate>{options.YearEndDate}</FinancialYearEndDate>");
        sb.AppendLine("    <Currency>INR</Currency>");
        sb.AppendLine("  </CompanyProfile>");
        sb.AppendLine($"  <Taggings count=\"{facts.Count}\">");

        foreach (var fact in facts)
        {
            sb.AppendLine($"    <Fact sagFieldId=\"{EscapeXml(fact.SagFieldId)}\" sagScreenRef=\"{EscapeXml(fact.SagScreenRef)}\" concept=\"{EscapeXml(fact.ConceptName)}\" schedule=\"{EscapeXml(fact.Schedule)}\" period=\"{EscapeXml(fact.Period)}\" unit=\"{EscapeXml(fact.Unit)}\" status=\"{fact.Status}\" confidence=\"{fact.Confidence}\">");
            sb.AppendLine($"      <Label>{EscapeXml(fact.Label)}</Label>");
            sb.AppendLine($"      <CurrentYearValue>{EscapeXml(fact.CurrentValue)}</CurrentYearValue>");
            sb.AppendLine($"      <PreviousYearValue>{EscapeXml(fact.PreviousValue)}</PreviousYearValue>");
            sb.AppendLine($"      <SourceDocument>{EscapeXml(fact.SourceDoc)}</SourceDocument>");
            sb.AppendLine($"      <SourcePageOrSheet>{EscapeXml(fact.SourcePageOrSheet)}</SourcePageOrSheet>");
            sb.AppendLine("    </Fact>");
        }

        sb.AppendLine("  </Taggings>");
        sb.AppendLine("  <AutomationBridge>");
        sb.AppendLine("    <SagAutoFillEnabled>true</SagAutoFillEnabled>");
        sb.AppendLine("    <PreservePriorYearDimensions>true</PreservePriorYearDimensions>");
        sb.AppendLine("    <DirectDatabaseWriteSupported>true</DirectDatabaseWriteSupported>");
        sb.AppendLine("  </AutomationBridge>");
        sb.AppendLine("</SAGGenXBRLExport>");

        return sb.ToString();
    }

    public static string GenerateMcaXml(IReadOnlyList<MappedFact> facts, SagExportOptions options)
    {
        var isIndAs = options.Taxonomy == TaxonomyStandard.IndAS;
        var pfx = isIndAs ? "ind-as" : "in-ca";
        var schemaRef = isIndAs
            ? "http://www.mca.gov.in/XBRL/2016/IndAS/ind-as_cor_2016-03-31.xsd"
            : "http://www.mca.gov.in/XBRL/2015/NonIndAS/in-ca_cor_2015-03-31.xsd";
        var ns = isIndAs
            ? "http://www.mca.gov.in/XBRL/2016/IndAS"
            : "http://www.mca.gov.in/XBRL/2015/NonIndAS";

        var decimals = options.UnitScale switch
        {
            "LAKHS" => "-5",
            "CRORES" => "-7",
            _ => "0"
        };

        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine("<!-- MCA Form AOC-4 XBRL Instance Document -->");
        sb.AppendLine("<!-- Generated by XBRL AI Agent for Ministry of Corporate Affairs (MCA) Portal -->");
        sb.AppendLine($"<xbrli:xbrl xmlns:{pfx}=\"{ns}\"");
        sb.AppendLine("  xmlns:xbrli=\"http://www.xbrl.org/2003/instance\"");
        sb.AppendLine("  xmlns:link=\"http://www.xbrl.org/2003/linkbase\"");
        sb.AppendLine("  xmlns:xlink=\"http://www.w3.org/1999/xlink\"");
        sb.AppendLine("  xmlns:iso4217=\"http://www.xbrl.org/2003/iso4217\">");
        sb.AppendLine($"  <link:schemaRef xlink:type=\"simple\" xlink:href=\"{schemaRef}\" />");
        sb.AppendLine();
        sb.AppendLine("  <!-- Unit Definitions -->");
        sb.AppendLine("  <xbrli:unit id=\"INR\">");
        sb.AppendLine("    <xbrli:measure>iso4217:INR</xbrli:measure>");
        sb.AppendLine("  </xbrli:unit>");
        sb.AppendLine("  <xbrli:unit id=\"pure\">");
        sb.AppendLine("    <xbrli:measure>xbrli:pure</xbrli:measure>");
        sb.AppendLine("  </xbrli:unit>");
        sb.AppendLine();
        sb.AppendLine("  <!-- Instant Context (CY Balance Sheet) -->");
        sb.AppendLine("  <xbrli:context id=\"CY_Instant\">");
        sb.AppendLine("    <xbrli:entity>");
        sb.AppendLine($"      <xbrli:identifier scheme=\"http://www.mca.gov.in/CIN\">{EscapeXml(options.CompanyCin)}</xbrli:identifier>");
        sb.AppendLine("    </xbrli:entity>");
        sb.AppendLine("    <xbrli:period>");
        sb.AppendLine($"      <xbrli:instant>{options.YearEndDate}</xbrli:instant>");
        sb.AppendLine("    </xbrli:period>");
        sb.AppendLine("  </xbrli:context>");
        sb.AppendLine();
        sb.AppendLine("  <!-- Duration Context (CY Profit & Loss) -->");
        sb.AppendLine("  <xbrli:context id=\"CY_Duration\">");
        sb.AppendLine("    <xbrli:entity>");
        sb.AppendLine($"      <xbrli:identifier scheme=\"http://www.mca.gov.in/CIN\">{EscapeXml(options.CompanyCin)}</xbrli:identifier>");
        sb.AppendLine("    </xbrli:entity>");
        sb.AppendLine("    <xbrli:period>");
        sb.AppendLine($"      <xbrli:startDate>{options.YearStartDate}</xbrli:startDate>");
        sb.AppendLine($"      <xbrli:endDate>{options.YearEndDate}</xbrli:endDate>");
        sb.AppendLine("    </xbrli:period>");
        sb.AppendLine("  </xbrli:context>");
        sb.AppendLine();
        sb.AppendLine("  <!-- Tagged Facts -->");

        foreach (var fact in facts)
        {
            var isDuration = fact.Period.Contains("Duration", StringComparison.OrdinalIgnoreCase) ||
                             fact.Schedule is "PROFIT_LOSS" or "CARO";
            var contextRef = isDuration ? "CY_Duration" : "CY_Instant";
            var tag = fact.ConceptName;

            if (fact.Unit == "string")
            {
                sb.AppendLine($"  <{tag} contextRef=\"{contextRef}\">{EscapeXml(fact.CurrentValue)}</{tag}>");
            }
            else
            {
                var unitRef = fact.Unit == "pure" ? "pure" : "INR";
                var dec = fact.Unit == "pure" ? "2" : decimals;
                sb.AppendLine($"  <{tag} contextRef=\"{contextRef}\" unitRef=\"{unitRef}\" decimals=\"{dec}\">{fact.CurrentValue}</{tag}>");
            }
        }

        sb.AppendLine("</xbrli:xbrl>");
        return sb.ToString();
    }

    public static string GenerateCsv(IReadOnlyList<MappedFact> facts, SagExportOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine("SAG_Field_ID,SAG_Screen_Reference,Concept_Code,Concept_Description,Schedule_Name,Period_Context,Current_Year_Value,Previous_Year_Value,Monetary_Unit,Decimals,Mapping_Status,Confidence_Score,Source_Document,Source_Page_Or_Sheet,Company_CIN,Taxonomy_Standard");

        var decimals = options.UnitScale switch
        {
            "LAKHS" => "-5",
            "CRORES" => "-7",
            _ => "0"
        };

        foreach (var fact in facts)
        {
            var isDuration = fact.Period.Contains("Duration", StringComparison.OrdinalIgnoreCase) ||
                             fact.Schedule is "PROFIT_LOSS" or "CARO";
            var dec = fact.Unit == "INR" ? decimals : (fact.Unit == "pure" ? "2" : "0");

            var row = new[]
            {
                EscapeCsv(fact.SagFieldId),
                EscapeCsv(fact.SagScreenRef),
                EscapeCsv(fact.ConceptName),
                EscapeCsv(fact.Label),
                EscapeCsv(fact.Schedule),
                isDuration ? "Duration" : "Instant",
                EscapeCsv(fact.CurrentValue),
                EscapeCsv(fact.PreviousValue),
                EscapeCsv(fact.Unit),
                dec,
                fact.Status.ToString(),
                $"{fact.Confidence}%",
                EscapeCsv(fact.SourceDoc),
                EscapeCsv(fact.SourcePageOrSheet),
                EscapeCsv(options.CompanyCin),
                options.Taxonomy.ToString()
            };

            sb.AppendLine(string.Join(",", row));
        }

        return sb.ToString();
    }

    public static string GenerateJson(IReadOnlyList<MappedFact> facts, SagExportOptions options)
    {
        var decimals = options.UnitScale switch
        {
            "LAKHS" => -5,
            "CRORES" => -7,
            _ => 0
        };

        var root = new
        {
            schemaVersion = "SAG_GENXBRL_2024.2",
            format = "SAG_XBRL_DATA_BRIDGE_JSON",
            generator = "XBRL_AI_Agent_Windows",
            exportedAt = DateTime.UtcNow.ToString("O"),
            companyProfile = new
            {
                cin = options.CompanyCin,
                companyName = options.CompanyName,
                financialYearStart = options.YearStartDate,
                financialYearEnd = options.YearEndDate,
                taxonomyStandard = options.Taxonomy.ToString(),
                natureOfReport = options.NatureOfReport,
                unitScale = options.UnitScale,
                currency = "INR",
                defaultDecimals = decimals
            },
            statistics = new
            {
                totalFacts = facts.Count,
                confirmedFacts = facts.Count(f => f.Status == MappingStatus.CONFIRMED),
                changedFacts = facts.Count(f => f.Status == MappingStatus.CHANGED),
                reviewRequiredFacts = facts.Count(f => f.Status == MappingStatus.REVIEW_REQUIRED)
            },
            taggings = facts.Select(f => new
            {
                sagFieldId = f.SagFieldId,
                sagScreenRef = f.SagScreenRef,
                conceptCode = f.ConceptName,
                label = f.Label,
                schedule = f.Schedule,
                period = f.Period,
                unit = f.Unit,
                decimals = f.Unit == "INR" ? decimals : 0,
                currentYearValue = f.CurrentValue,
                previousYearValue = f.PreviousValue,
                status = f.Status.ToString(),
                confidence = f.Confidence,
                sourceDocument = f.SourceDoc,
                sourcePageOrSheet = f.SourcePageOrSheet
            })
        };

        return JsonSerializer.Serialize(root, new JsonSerializerOptions { WriteIndented = true });
    }

    public static string GeneratePowerShell(SagExportOptions options)
    {
        return $@"<#
.SYNOPSIS
    Automated Data Injector for SAG Gen XBRL
    Company: {options.CompanyName} (CIN: {options.CompanyCin})
#>

Write-Host ""=== XBRL AI AGENT: SAG GEN XBRL AUTO-WRITER ==="" -ForegroundColor Cyan
Write-Host ""Target Company: {options.CompanyName}"" -ForegroundColor Yellow
Write-Host ""CIN: {options.CompanyCin}"" -ForegroundColor Yellow

$sagPaths = @(
    ""C:\Program Files\SAG Infotech\GenXBRL\GenXBRL.exe"",
    ""C:\Program Files (x86)\SAG Infotech\GenXBRL\GenXBRL.exe"",
    ""M:\SAG Infotech\GenXBRL\GenXBRL.exe""
)

$sagExe = $sagPaths | Where-Object {{ Test-Path $_ }} | Select-Object -First 1

if (-not $sagExe) {{
    Write-Warning ""SAG Gen XBRL executable not found in default paths.""
    Write-Host ""Looking for active GenXBRL process...""
    $proc = Get-Process -Name ""GenXBRL"" -ErrorAction SilentlyContinue
    if ($proc) {{
        $sagExe = $proc.Path
        Write-Host ""Found running Gen XBRL process: $sagExe"" -ForegroundColor Green
    }}
}}

$importCsv = Join-Path $PSScriptRoot ""SAG_GenXBRL_Mapping_{options.CompanyCin}.csv""
$importXag = Join-Path $PSScriptRoot ""SAG_GenXBRL_{options.CompanyCin}.xag""

Write-Host ""Auto-fill files prepared:"" -ForegroundColor Green
Write-Host "" - CSV: $importCsv""
Write-Host "" - XAG: $importXag""
Write-Host ""Ready to inject into SAG Gen XBRL."" -ForegroundColor Cyan
";
    }

    public static string GenerateAutoHotkey(SagExportOptions options)
    {
        return $@"; AutoHotkey Macro for SAG Gen XBRL Robotic Auto-Fill
; Company: {options.CompanyName} (CIN: {options.CompanyCin})

SetTitleMatchMode, 2
WinTitle := ""Gen XBRL""

IfWinExist, %WinTitle%
{{
    WinActivate, %WinTitle%
    WinWaitActive, %WinTitle%, , 3
    Sleep, 500
    
    ; Trigger Import Menu (Alt+T -> Import)
    Send, !t
    Sleep, 300
    Send, i
    Sleep, 300
    Send, {{Enter}}
    Sleep, 800
    
    TrayTip, XBRL AI Agent, SAG Gen XBRL Import sequence initiated!, 5
}}
Else
{{
    MsgBox, 48, SAG Gen XBRL Not Running, Please open SAG Gen XBRL first, then re-run this script to auto-fill.
}}
Return
";
    }

    private static string EscapeXml(string val) =>
        (val ?? "")
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");

    private static string EscapeCsv(string val)
    {
        val ??= "";
        if (val.Contains(',') || val.Contains('"') || val.Contains('\n') || val.Contains('\r'))
            return $"\"{val.Replace("\"", "\"\"")}\"";
        return val;
    }
}
